name: Mirror to GitLab

on:
  push:
    branches:
      - stable

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote
        run: git remote add gitlab ${{ secrets.GITLAB_REMOTE_URL }}

      - name: Push changed branch to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITLAB_REMOTE_URL: ${{ secrets.GITLAB_REMOTE_URL }}
        run: |
          git push --force https://oauth2:${GITLAB_TOKEN}@${GITLAB_REMOTE_URL#https://}
