# .github/workflows/mirror.yml
name: Mirror to personal repo

on:
  push:
    branches:
      - stable
      - stage

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repo
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_REPO_TOKEN }}@github.com/katharinadobiosch/makaira-asset-manager.git
          git push mirror stable
          git push mirror stage